import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import "tailwindcss/tailwind.css";

const Home: NextPage = () => {
  const router = useRouter();
  // console.log("router");
  // console.log(router);

  const baseLink = "short.app";
  const generatedLink = "Mwfwk4rREF32c";
  return (
    <div>
      <Head>
        <title>Link Shortener</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-slate-900 flex flex-col space-y-4 justify-center items-center text-2xl h-screen px-3">
        <div
          className="w-full space-y-4"
          style={{
            maxWidth: "600px",
          }}
        >
          <div className="flex items-center space-x-2 w-full justify-center">
            <input
              className="border-gray-600 focus:border-gray-400 text-white bg-slate-800 w-4/5 p-3 border-2 rounded-lg focus:shadow-lg outline-0"
              placeholder="https://google.com"
              type="text"
              onChange={() => console.log()}
            />
            <button className="text-white w-1/5 bg-indigo-600 hover:bg-indigo-500 flex justify-center rounded-lg py-3 font-semibold shadow-lg">
              Shorten
            </button>
          </div>
          <div className="flex items-center space-x-2 w-full justify-center">
            <div className="w-9/12 flex items-center space-x-2">
              <p className="text-white w-2/5">https://{baseLink}/</p>
              <input
                className="border-gray-600 focus:border-gray-400 text-white bg-slate-800 w-3/5 p-3 border-2 rounded-lg focus:shadow-lg outline-0"
                type="text"
                value={generatedLink}
                onChange={() => console.log()}
              />
            </div>
            <button className="w-1/12 bg-indigo-600 hover:bg-indigo-500 flex justify-center rounded-lg py-3 shadow-lg">
              <img src="retry.svg" className="w-9 h-8" />
            </button>
            <button className="text-white w-2/12 bg-indigo-600 hover:bg-indigo-500 flex justify-center rounded-lg py-3 font-semibold shadow-lg">
              Save
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
